### PR TITLE
Set version.m4 to 2.0.0

### LINKED ISSUE #43: Building EOS app on EOS SDK 2.0.0 incorrectly links to libeos.so.1.13
**Problem:**
Building EOS Apps against EosSDK 2.0.0 are improperly linking to libeos.so.1.13, it should be 2.0.0.

**Steps to reproduce**
1) Obtain the EosSdk source code.
2) run `./build.sh` to compile the example applications.
3) run `ldd .libs/HelloWorld`
```
:~/2.0/EosSdk-2.0.0/.libs$ ldd HelloWorld
        linux-gate.so.1 =>  (0xf7796000)
        libeos.so.1.13 => not found <-------------
        libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xf769a000)
        libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf767d000)
        libc.so.6 => /lib32/libc.so.6 (0xf74cf000)
        libm.so.6 => /lib32/libm.so.6 (0xf7488000)
        /lib/ld-linux.so.2 (0xf7797000)
```

**Expected result**
This should be linked to libeos.so.2.0.0, or at least libeos.so.2. 

On an EOS switch, this is unavailable:
```
$ ls -lah /usr/lib/libeos*
lrwxrwxrwx 1 root root   15 Nov 21 21:15 /usr/lib/libeos.so -> libeos.so.2.0.0
lrwxrwxrwx 1 root root   15 Nov 21 21:15 /usr/lib/libeos.so.2 -> libeos.so.2.0.0
lrwxrwxrwx 1 root root   15 Nov 21 21:15 /usr/lib/libeos.so.2.0 -> libeos.so.2.0.0
-rwxr-xr-x 1 root root 3.9M Nov 20 22:19 /usr/lib/libeos.so.2.0.0
```

### PR DESCRIPTION
**Pull request by jpsenior**
Set version to 2.0.0 for libeos stub library.

@avi-kumar -- this one-liner let me build my app properly. I'm sure there's probably more upstream syncs necessary :)

Fixes #43

### CODE REVIEW

**Comment by avi-kumar** [comment]
Ah sorry about that, must have gotten unstaged before pushing! Thanks for patching!

**Comment by jpsenior** [comment]
Thanks @avi-kumar  - will this automatically build new release artifacts? (.tar.gz) ?

**Comment by avi-kumar** [comment]
I have updated the 2.0.0 release to include this in the release tarball. Please let us know if you still have issues. Thanks!

**Comment by jpsenior** [comment]
This is the best release yet! Didn't have to patch anything, thank you @avi-kumar this is excellent

**Pull request merged**
